Add files via upload
giacomodecolle/CCO-design-patterns pull request #1
Opened 2024-11-18 21:50 UTC by gregfowlerphd

2024-11-19 15:45 UTC, giacomodecolle requested changes

2024-11-19 15:45 UTC, giacomodecolle commented on design-patterns/time/CCO DP, p. 17.md
> +graph TD
change to BT

2024-11-19 15:45 UTC, giacomodecolle commented on design-patterns/time/CCO DP, p. 17.md
> +    classDef yellow fill:#EDF2AE
change yellow code

2024-11-21 15:19 UTC, gregfowlerphd commented
@giacomodecolle: Requested changes made.

2024-11-26 15:13 UTC, giacomodecolle requested changes

2024-11-26 15:13 UTC, giacomodecolle commented on design-patterns/time/CCO DP, p. 17.md
>      C -->|rdf:type| E[Temporal Instant BFO_0000063]
Change BFO number

2024-11-26 19:34 UTC, gregfowlerphd commented on design-patterns/time/CCO DP, p. 17.md
>      C -->|rdf:type| E[Temporal Instant BFO_0000063]
Done.

2024-12-03 15:38 UTC, giacomodecolle commented
Changing name of files to something like "first and last temporal instant"

2024-12-06 18:15 UTC, gregfowlerphd commented
-Deleted misnamed Markdown and PNG files
-Uploaded correctly named files
-Content of new files changed to specific examples

2024-12-10 15:47 UTC, merged